# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-06 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/courses/pictures'),
        ),
    ]
